### ISSUE TITLE
Add section to code on how to send mouse clicks

### ISSUE THREAD

**Issue by emuston-firsch** [Hermiedapwdrman/CH_Myoware#3]
Code is currently very easily modified to send different keyboard commands. would be nice to have a section explaining how to easily add a command to have the device send a left mouse click to computer. Or even to have the left mouse click command added behind "//" so that users can just delete "//" to make it work (if that makes sense)

**Comment by Hermiedapwdrman** [comment]
This shouldn't be hard, I will put the key press as well as the mouse click together in the code.

**Comment by Hermiedapwdrman** [comment]
Looking at the code I see two ways to do this:
1) We have a variable you set in the code next to the output character.  If true it will click the mouse button, if false it will not.  The mouse click will be enabled when you toggle the enable switch(pin 12)

2) We add another, separate physical enable switch.  P We could make pin 11 or some other IO pin enable the mouse click.  Pin 12 currently enables the keyboard.

Thoughts?

**Comment by emuston-firsch** [comment]
Hmm, two good options. I think I prefer the second option as it allows for a quick switch on the fly without getting back into the code. Thanks!

**Comment by emuston-firsch** [comment]
Just tested and this works great. Thanks!
